apps/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.UserRegisterView.as_view(),name='register'),
    path('login/', views.login_view,name='login'),
    path('logout/', views.LogoutView.as_view(),name='logout'),
    # path('profile/', views.profile,name='profile'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.users.urls')),
]

apps/main/models.py
from django.db import models

# Create your models here.

apps/posts/models.py
from django.db import models

# Create your models here.

apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.urls import reverse

from .managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField('Email', max_length=255, unique=True)
    first_name = models.CharField('Nombres', max_length=50, blank=True, null=True)
    last_name = models.CharField('Apellidos', max_length=50, blank=True, null=True)
    avatar = models.ImageField('Imagen', upload_to='profile/', max_length=255, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()

    class Meta:
        verbose_name = 'Usuario'
        verbose_name_plural = 'Usuarios'

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    # def get_absolute_url(self):
    #     return reverse('', kwargs={'pk': self.pk})

    def __str__(self):
        return f'{self.email}'

apps/users/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth import authenticate

from .models import User


# Forms for admin
class UserCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        # fileds = '__all__'
        fields = ('email', 'password', 'first_name', 'last_name', 'avatar', 'is_active', 'is_staff')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError("Las contraseñas no coinciden.")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserRegisterForm(forms.ModelForm):

    password1 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Contraseña'
            }
        )
    )
    password2 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Confirmar Contraseña'
            }
        )
    )

    class Meta:
        """Meta definition for UserForm"""
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
        )
        widgets = {
            'email': forms.EmailInput(
                attrs = {
                    'placeholder': 'Correo Electrónico...'
                }
            ),
            'first_name': forms.TextInput(
                attrs = {
                    'placeholder': 'Nombres...'
                }
            ),
            'last_name': forms.TextInput(
                attrs = {
                    'placeholder': 'Apellidos...'
                }
            )
        }

    def clean_password2(self):
        if self.cleaned_data['password1'] != self.cleaned_data['password2']:
            self.add_error('password2', 'Las contraseñas no coinciden.')


class LoginForm(forms.Form):
    email = forms.CharField(
        label='Email',
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Correo Electronico',
            }
        )
    )
    password = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'contraseña'
            }
        )
    )

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        email = self.cleaned_data['email']
        password = self.cleaned_data['password']

        if not authenticate(email=email, password=password):
            raise forms.ValidationError('Los datos de usuario no son correctos.')
        
        return self.cleaned_data

apps/main/views.py
from django.shortcuts import render

# Create your views here.

apps/posts/views.py
from django.shortcuts import render

# Create your views here.

apps/users/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View,CreateView
from django.views.generic.edit import FormView

#
from .forms import LoginForm, UserRegisterForm # UpdatePasswordForm,)
from .models import User

def home(request):
    return render(request, 'home.html', {})

def profile(request):
    return render(request, 'profile.html', {})


class UserRegisterView(FormView):
    template_name = 'users/register.html'
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        #
        User.objects.create_user(
            form.cleaned_data['email'],
            form.cleaned_data['first_name'],
            form.cleaned_data['last_name'],
            form.cleaned_data['password1'],
        )
        return super(UserRegisterView, self).form_valid(form)


def login_view(request):

    form = LoginForm(request.POST or None)

    if form.is_valid():
        email=form.cleaned_data.get('email')
        password=form.cleaned_data.get('password')
        user = authenticate(request, email=email, password=password)

        if user is not None:
            login(request, user)

            if user.is_active and user.is_superuser:
                return HttpResponseRedirect(reverse_lazy('admin:index'))
            elif user.is_active:      
                return HttpResponseRedirect(reverse_lazy('users:home'))
    
    return render(request, 'users/login.html', {'form': form})


class LogoutView(View, LoginRequiredMixin):
    def get(self, request, *args, **kargs):
        logout(request)
        return HttpResponseRedirect( 
            reverse(
                'users:home'
            )
        )

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Código Libre{% endblock title %}</title>
    <meta name="description" content="Página de blog dedicada a compartir contenido sobre programación y desarrollo web.">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <!-- <link rel="stylesheet" href="{% static 'css/styles.css' %}"> -->
    {% block extra_css %}{% endblock extra_css %}
</head>
<body>
   
   {% comment %}
    <header class="">
        <nav class="navbar navbar-expand-lg">
            <div class="container-fluid d-flex justify-content-between">
                <a class="navbar-brand" href="#">
                    <img src="{% static 'img/logo.png' %}" alt="" height="50" width="200">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarScroll">
                    <ul class="navbar-nav me-2 my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 200px;">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        
        <section class="hero">
            <div class="container">
                {% block hero %}
                    <h1 class="display-4 fw-bold hero-title">Blog de Programación y Tecnología</h1>
                    <p class="lead mb-4 fw-bolder fs-2">
                        By dev for devs
                    </p>
                {% endblock hero %}
            </div>
        </section>
    </header>
    {% endcomment %}

    <main class="py-5">
        {% block content %} {% endblock content %}
    </main> 

    <footer>
        {% block footer %} {% endblock footer %}
    </footer>
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>

    <!-- <script>
        const nav = document.querySelector('.navbar')

        window.addEventListener('scroll', function(){
            nav.classList.toggle('act_scroll', window.scrollY > 0);
        })
    </script> -->
</body>
</html>

templates/home.html
{% extends 'base/base.html' %}


{% block content %}
    <h1>Página Principal</h1>
    
    
    {% if user.is_authenticated %}
    <p>Bienvenido {{user}}</p>
    <a href="{% url 'users:logout' %}" >Cerrar Sesión</a>
    {% else %}
    <a href="{% url 'users:login' %}">Inicia Sesión</a>
    {% endif %}
        
{% endblock content %}
    

templates/users/login.html
{% extends 'base/base.html' %}

{% block title %}Login{% endblock title %}
    
{% block content %}

<h1>Inicio de Sesión</h1>

<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}

    <button type="submit">Login</button>
</form>
<p>No tienes una cuenta? <a href="{% url 'users:register' %}">Regístrate</a></p>
{% endblock content %}

templates/users/register.html
{% extends 'base/base.html' %}

{% block title %}Register{% endblock title %}
    
{% block content %}

<h1>Registro de usuario</h1>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}

    <button type="submit">Registrar</button>
</form>
{% endblock content %}